name: Backend Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  QR service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build QR service with Maven
        working-directory: ./backend/QR-service
        run: mvn -B package --file pom.xml
      - name: Test QR service with Maven
        working-directory: ./backend/QR-service
        run: mvn test
  
  Restaurant service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build restaurant service with Maven
        working-directory: ./backend/restaurant-service
        run: mvn -B package --file pom.xml
      - name: Test restaurant service with Maven
        working-directory: ./backend/restaurant-service
        run: mvn test
  
  Menu service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build menu service with Maven
        working-directory: ./backend/menu-service
        run: mvn -B package --file pom.xml
      - name: Test menu service with Maven
        working-directory: ./backend/menu-service
        run: mvn test
      
  Order service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build order service with Maven
        working-directory: ./backend/order-service
        run: mvn -B package --file pom.xml
      - name: Test order service with Maven
        working-directory: ./backend/order-service
        run: mvn test
  
  Discovery server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build discover server with Maven
        working-directory: ./backend/discovery-server
        run: mvn -B package --file pom.xml
      - name: Test discovery server with Maven
        working-directory: ./backend/discovery-server
        run: mvn test

  Gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build gateway with Maven
        working-directory: ./backend/gateway
        run: mvn -B package --file pom.xml
      - name: Test gateway with Maven
        working-directory: ./backend/gateway
        run: mvn test
